export const formSchemaJson = {
    versions: [
        {
            sections: [
                {
                    is_disabled: false,
                    is_repeatable: false,
                    meta_data: {},
                    order: 1,
                    questions: [
                        {
                            _id: "3459de79-5803-489c-8c9c-3fff24335933",
                            field_type: "input",
                            is_disabled: false,
                            is_repeatable: false,
                            is_required: true,
                            meta_data: {},
                            options: [],
                            repeat_min: 0,
                            label: "Name",
                            visible_header: false,
                        },
                        {
                            _id: "af234364-d84f-4c08-861c-4ba9f2c10951",
                            field_type: "input",
                            is_disabled: false,
                            is_repeatable: false,
                            is_required: true,
                            meta_data: {},
                            options: [],
                            repeat_min: 0,
                            label: "Age",
                            visible_header: false,
                        },
                        {
                            _id: "91deaef0-dfc6-43ac-adff-dedbd739ae95",
                            field_type: "radio",
                            is_disabled: false,
                            is_repeatable: false,
                            is_required: true,
                            meta_data: {},
                            options: [
                                {
                                    _id: "b5d05fa7-cf03-4153-bef7-3e256d68ac9a",
                                    is_default: false,
                                    is_disabled: false,
                                    option_label: "Male",
                                    option_value: "M",
                                    order: 0,
                                },
                                {
                                    _id: "9681e528-8986-482c-bee2-7d7c4baa4cd0",
                                    is_default: false,
                                    is_disabled: false,
                                    option_label: "Female",
                                    option_value: "F",
                                    order: 0,
                                },
                                {
                                    _id: "6889b9cb-962c-45e6-9b36-19b776ed3bed",
                                    is_default: false,
                                    is_disabled: false,
                                    option_label: "Other",
                                    option_value: "O",
                                    order: 0,
                                },
                            ],
                            repeat_min: 0,
                            label: "Sex",
                            visible_header: false,
                        },
                        {
                            _id: "baba0b79-d5bd-406e-8bd0-a88e8fa32933",
                            field_type: "input",
                            is_disabled: false,
                            is_repeatable: false,
                            is_required: false,
                            meta_data: {},
                            options: [],
                            repeat_min: 0,
                            label: "UHID",
                            visible_header: false,
                        },
                    ],
                    repeat_min: 0,
                    title: "Basic Information",
                    ui: "flex",
                },
            ],
        },
    ],
};
